---
title: "Facturas Seiton"
output: html_notebook
---

```{r paqueterias, include=FALSE}
library(tidyverse)
library(readxl)
library(lubridate)
library(tsibble)
library(feasts)
library(fable)
# library(tibble)
# library(ggplot2)
# library(dplyr)
```

```{r funciones}

read_excel_drop <- function(filename) {
  df <- read_excel(filename, col_names = TRUE, col_types = NULL)
  drop <- names(df) %in% c("CTRO PROD - IMPRESIONES BYN", "Bonificadas", "Renta fija")
  df[, !drop]
}

filtro_tibble <- function(tibble, fecha_col, paginas_col) {
  tibble %>%
    select(fecha_col, paginas_col) %>%
    rename(Fecha = {{fecha_col}}, Paginas = {{paginas_col}}) %>%
    filter(!is.na(as.Date(Fecha, format = "%d/%m/%y", 
                          tryFormats = c("%d-%m-%y","%Y-%m-%d")))) %>%
    group_by(Fecha) %>% 
    summarise(paginas_procesadas = sum(Paginas))
}

filtro_ventas <- function(tibble, fecha_col, folio_col, monto_col) {
  tibble %>%
    select(fecha_col, folio_col, monto_col) %>%
    rename(Fecha = {{fecha_col}}, Folio = {{folio_col}}, Monto = {{monto_col}}) %>%
    filter(!is.na(as.Date(Fecha, format = "%d/%m/%y", 
                          tryFormats = c("%d-%m-%y","%Y-%m-%d")))) %>%
    group_by(Folio) %>%
    group_by(Fecha) %>%
    summarise(`Total`=sum(mean(as.numeric(Monto)))
            )
}
```



```{r  carga de datos}

# Leer archivos y eliminar columnas no deseadas
Enero_2018 <- read_excel_drop("ReporteEquipoCosto_Enero_2018.xlsx")
Febrero_2018 <- read_excel_drop("ReporteEquipoCosto_Febrero_2018.xlsx")
Marzo_2018 <- read_excel_drop("ReporteEquipoCosto_Marzo_2018.xlsx")
Abril_2018 <- read_excel_drop("ReporteEquipoCosto_Abril_2018.xlsx")
Mayo_2018 <- read_excel_drop("ReporteEquipoCosto_Mayo_2018.xlsx")
Junio_2018 <- read_excel_drop("ReporteEquipoCosto_Junio_2018.xlsx")
Julio_2018 <- read_excel_drop("ReporteEquipoCosto_Julio_2018.xlsx")
Agosto_2018 <- read_excel_drop("ReporteEquipoCosto_Agosto_2018.xlsx")
Septiembre_2018 <- read_excel_drop("ReporteEquipoCosto_Septiembre_2018.xlsx")
Octubre_2018 <- read_excel_drop("ReporteEquipoCosto_Octubre_2018.xlsx")
Noviembre_2018 <- read_excel_drop("ReporteEquipoCosto_Noviembre_2018.xlsx")
Diciembre_2018 <- read_excel_drop("ReporteEquipoCosto_Diciembre_2018.xlsx")

Enero_2019 <- read_excel_drop("ReporteEquipoCosto_Enero_2019.xlsx")
Febrero_2019 <- read_excel_drop("ReporteEquipoCosto_Febrero_2019.xlsx")
Marzo_2019 <- read_excel_drop("ReporteEquipoCosto_Marzo_2019.xlsx")
Abril_2019 <- read_excel_drop("ReporteEquipoCosto_Abril_2019.xlsx")
Mayo_2019 <- read_excel_drop("ReporteEquipoCosto_Mayo_2019.xlsx")
Junio_2019 <- read_excel_drop("ReporteEquipoCosto_Junio_2019.xlsx")
Julio_2019 <- read_excel_drop("ReporteEquipoCosto_Julio_2019.xlsx")
Agosto_2019 <- read_excel_drop("ReporteEquipoCosto_Agosto_2019.xlsx")
Septiembre_2019 <- read_excel_drop("ReporteEquipoCosto_Septiembre_2019.xlsx")
Octubre_2019 <- read_excel_drop("ReporteEquipoCosto_Octubre_2019.xlsx")
Noviembre_2019 <- read_excel_drop("ReporteEquipoCosto_Noviembre_2019.xlsx")
Diciembre_2019 <- read_excel_drop("ReporteEquipoCosto_Diciembre_2019.xlsx")

Enero_2020 <- read_excel_drop("ReporteEquipoCosto_Enero_2020.xlsx")
Febrero_2020 <- read_excel_drop("ReporteEquipoCosto_Febrero_2020.xlsx")
Marzo_2020 <- read_excel_drop("ReporteEquipoCosto_Marzo_2020.xlsx")
Abril_2020 <- read_excel_drop("ReporteEquipoCosto_Abril_2020.xlsx")
Mayo_2020 <- read_excel_drop("ReporteEquipoCosto_Mayo_2020.xlsx")
Junio_2020 <- read_excel_drop("ReporteEquipoCosto_Junio_2020.xlsx")
Julio_2020 <- read_excel_drop("ReporteEquipoCosto_Julio_2020.xlsx")
Agosto_2020 <- read_excel_drop("ReporteEquipoCosto_Agosto_2020.xlsx")
```



```{r tablas anuales}
Ano_2018 <- rbind(Enero_2018,Febrero_2018,Marzo_2018,Abril_2018,Mayo_2018,Junio_2018,
                Julio_2018,Agosto_2018,Septiembre_2018,Octubre_2018,Noviembre_2018,
                Diciembre_2018)

Ano_2019 <- rbind(Enero_2019,Febrero_2019,Marzo_2019,Abril_2019,Mayo_2019,Junio_2019,
                Julio_2019,Agosto_2019,Septiembre_2019,Octubre_2019,Noviembre_2019,
                Diciembre_2019)

Ano_2020 <- rbind(Enero_2020,Febrero_2020,Marzo_2020,Abril_2020,Mayo_2020,Junio_2020,
                Julio_2020,Agosto_2020)
```

```{r Tabla Total}
TablaT <- rbind(Ano_2018,Ano_2019,Ano_2020)
TablaT

TablaT %>% 
  select(Facturado)

TablaT %>% 
  mutate(
    fecha = if_else(is.na(dmy(Facturado)),
                    as.Date(as.numeric(Facturado), origin = "1899-12-30"),
                    dmy(Facturado)) 
  ) %>% 
  janitor::make_clean_names()
```

```{r Paginas procesadas por año}
# Filtrar con la función anterior
pp_2018 <- filtro_tibble(Ano_2018, "Facturado", "Total páginas procesadas")
pp_2018$Fecha <- as.POSIXct(pp_2018$Fecha, format = "%d/%m/%Y") #Cambio de formato de fecha, para unificar

pp_2019 <- filtro_tibble(Ano_2019, "Facturado", "Total páginas procesadas")
pp_2019$Fecha <- as.POSIXct(pp_2019$Fecha, format = "%d/%m/%Y") #Cambio de formato de fecha, para unificar

pp_2020 <- filtro_tibble(Ano_2020, "Facturado", "Total páginas procesadas")
pp_2020$Fecha <- as.POSIXct(pp_2020$Fecha, format = "%d/%m/%Y") #Cambio de formato de fecha, para unificar

ppT <- filtro_tibble(TablaT, "Facturado", "Total páginas procesadas")
ppT$Fecha <- as.POSIXct(ppT$Fecha, format = "%d/%m/%Y") #Cambio de formato de fecha, para unificar
```

Convertir tibbles a tsibble
```{r}

#Convertido a tsibble
pp_2018_ts<- as_tsibble(pp_2018, index = Fecha)
pp_2019_ts<- as_tsibble(pp_2019, index = Fecha)
pp_2020_ts<- as_tsibble(pp_2020, index = Fecha)
ppT_ts<- as_tsibble(ppT, index = Fecha)
```

```{r graficas paginas procesadas}
ggplot(pp_2018, aes(x = Fecha, y = paginas_procesadas)) +
  geom_line() +
  labs(title = "Páginas procesadas en 2018",
       x = "Fecha",
       y = "Páginas procesadas")

ggplot(pp_2019, aes(x = Fecha, y = paginas_procesadas)) +
  geom_line() +
  labs(title = "Páginas procesadas en 2019",
       x = "Fecha",
       y = "Páginas procesadas")

ggplot(pp_2020, aes(x = Fecha, y = paginas_procesadas)) +
  geom_line() +
  labs(title = "Páginas procesadas en 2020",
       x = "Fecha",
       y = "Páginas procesadas")

ggplot(ppT, aes(x = Fecha, y = paginas_procesadas)) +
  geom_line() +
  labs(title = "Páginas procesadas en todo el tiempo",
       x = "Fecha",
       y = "Páginas procesadas")

```

```{r Ventas facturadas por año }
Ventas_2018 <- filtro_ventas(Ano_2018, "Facturado", "Folio", "Total")
Ventas_2018$Fecha <- as.POSIXct(Ventas_2018$Fecha, format = "%d/%m/%Y") #Cambio de formato de fecha, para unificar

Ventas_2019 <- filtro_ventas(Ano_2019, "Facturado", "Folio", "Total")
Ventas_2019$Fecha <- as.POSIXct(Ventas_2019$Fecha, format = "%d/%m/%Y") #Cambio de formato de fecha, para unificar

Ventas_2020 <- filtro_ventas(Ano_2020, "Facturado", "Folio", "Total")
Ventas_2020$Fecha <- as.POSIXct(Ventas_2020$Fecha, format = "%d/%m/%Y") #Cambio de formato de fecha, para unificar

VentasT <- filtro_ventas(TablaT, "Facturado", "Folio", "Total")
VentasT$Fecha <- as.POSIXct(VentasT$Fecha, format = "%d/%m/%Y") #Cambio de formato de fecha, para unificar
```

Convertir tibbles a tsibble
```{r}

#Convertido a tsibble
Ventas_2018_ts<- as_tsibble(Ventas_2018, index = Fecha)
Ventas_2019_ts<- as_tsibble(Ventas_2019, index = Fecha)
Ventas_2020_ts<- as_tsibble(Ventas_2020, index = Fecha)
VentasT_ts<- as_tsibble(VentasT, index = Fecha)
```

```{r graficas de ventas facturadas}
ggplot(Ventas_2018, aes(x = Fecha, y = Total)) +
  geom_line() +
  labs(title = "Ventas facturadas en 2018",
       x = "Fecha",
       y = "Monto")

ggplot(Ventas_2019, aes(x = Fecha, y = Total)) +
  geom_line() +
  labs(title = "Ventas facturadas en 2019",
       x = "Fecha",
       y = "Monto")

#ggplot(Ventas_2020, aes(x = Fecha, y = Total)) +
#  geom_line() +
#  labs(title = "Ventas facturadas en 2020",
 #      x = "Fecha",
  #     y = "Monto")

ggplot(VentasT, aes(x = Fecha, y = Total)) +
  geom_line() +
  labs(title = "Ventas totales facturadas al paso del tiempo",
       x = "Fecha",
       y = "Monto")
```









